
name: dev-ums
on:
  push:
    branches:
      - main

env:
  AWS_REGION: ap-south-1
  
jobs:
  build:
    name: semantic release
    runs-on: ubuntu-latest
    environment: main
    steps:
      - name: Checkout branch "main"
        uses: actions/checkout@v2
        with:
          ref: "main"
          fetch-depth: 0

      # - name: semantic configuration
      #   run: |
      #     cat > release.config.js <<- "EOF"
      #       module.exports={"branches":["development"],
      #       "repositoryUrl":"https://github.com/byjus-orders/microservices-ums",
      #       "plugins":[
      #         "@semantic-release/commit-analyzer",
      #         "@semantic-release/release-notes-generator",
      #         "@semantic-release/github"]}
      - name: create a release
        run: |
          npm i
          npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}