
name: dev-ums
on:
  push:
    branches:
      - development
    paths:
      - server/**

env:
  AWS_REGION: ap-south-1
  ECR_REPOSITORY: microservices-ums-image
  IMAGE_NAME: microservices-ums-image
  ECS_SERVICE: development-ums-service
  ECS_CLUSTER: development-locus-ecs-cluster
  ECS_TASK_DEFINITION: development-ums-td
  CONTAINER_NAME: development-ums-container
  COMMIT: 0
  TAG: 0
  SCHEMA_DIRECTORY: ums
jobs:
  build:
    name: semantic release
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Checkout branch "development"
        uses: actions/checkout@v2
        with:
          ref: "development"
          fetch-depth: 0

      # - name: semantic configuration
      #   run: |
      #     cat > release.config.js <<- "EOF"
      #       module.exports={"branches":["development"],
      #       "repositoryUrl":"https://github.com/byjus-orders/microservices-ums",
      #       "plugins":[
      #         "@semantic-release/commit-analyzer",
      #         "@semantic-release/release-notes-generator",
      #         "@semantic-release/github"]}
      - name: create a release
        run: |
          npm i
          npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}